// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9Sl5P6-lVw3nLKxsnzzT2T6aA3EEGW4',
    appId: '1:10210531174:web:acc252e0053f5fbae01aa7',
    messagingSenderId: '10210531174',
    projectId: 'pocket-nur',
    authDomain: 'pocket-nur.firebaseapp.com',
    storageBucket: 'pocket-nur.firebasestorage.app',
    measurementId: 'G-1WZDGC4TKM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAOBjyxhB9GOTq5HmTlQrTSeMlYflvq5E',
    appId: '1:10210531174:ios:97efea3dae70e4f6e01aa7',
    messagingSenderId: '10210531174',
    projectId: 'pocket-nur',
    storageBucket: 'pocket-nur.firebasestorage.app',
    iosBundleId: 'com.example.pocketNur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe9Sl5P6-lVw3nLKxsnzzT2T6aA3EEGW4',
    appId: '1:10210531174:web:4838a009e174ef68e01aa7',
    messagingSenderId: '10210531174',
    projectId: 'pocket-nur',
    authDomain: 'pocket-nur.firebaseapp.com',
    storageBucket: 'pocket-nur.firebasestorage.app',
    measurementId: 'G-GRTRC5RV26',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAOBjyxhB9GOTq5HmTlQrTSeMlYflvq5E',
    appId: '1:10210531174:ios:97efea3dae70e4f6e01aa7',
    messagingSenderId: '10210531174',
    projectId: 'pocket-nur',
    storageBucket: 'pocket-nur.firebasestorage.app',
    iosBundleId: 'com.example.pocketNur',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCubMclmFbUm3HkpmM4a5obbw1fbX2DQqs',
    appId: '1:10210531174:android:c23d7522042cde43e01aa7',
    messagingSenderId: '10210531174',
    projectId: 'pocket-nur',
    storageBucket: 'pocket-nur.firebasestorage.app',
  );

}